name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:

      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 3. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 4. Terraform Format
      - name: Terraform Format
        run: terraform fmt -check

      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 6. Terraform Apply (only on main repo, not from forks)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
